name: Automation Exercise CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Run Tests with Maven
        # Chạy headless vì GitHub Runner không có màn hình giao diện
        run: mvn clean test -Dheadless=true

      - name: Get Allure history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report Action
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: target/allure-results
          allure_history: allure-history

      - name: Deploy Allure Report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-history

      - name: Send Telegram Notification
        uses: appleboy/telegram-action@master
        if: always() # Luôn chạy kể cả test Pass hay Fail
        with:
          to: ${{ secrets.Telegram_To }}
          token: ${{ secrets.Telegram_Token }}
          format: html
          message: |
            <b>🚀 Kết quả chạy Test trên GitHub</b>
            <b>Dự án:</b> ${{ github.repository }}
            <b>Trạng thái:</b> ${{ job.status == 'success' && '✅ THÀNH CÔNG' || '❌ THẤT BẠI' }}
            <b>Link báo cáo:</b> https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}